#' @name saveParamDf
#' @rdname saveParamDf
#'
#' @title Helper functions for saving parameters randomly generated by scripPopMods
#' in order to compare simulated statistics against parameter values in tables and/or visualizations
#' @param paramList list of parameters generated by scriptPopMods
#' @param paramType character of what kind of parameters to save. Can be "structural", "measurement", or "both"
#'
#' @return data frame of parameter values styled to be rbind() friendly for output from runDySim (and `lavaan::parameterestimates` generally)
#' @family helpers

saveParamLAPIM <- function(paramList, paramType){

  if(paramType == "measurement"){

  }else if(paramType == "structural"){
    lhs <- c("YA", "YB", "YA", "YB", "k1", "k2")
    op <- c("~", "~", "~", "~", ":=", ":=")
    rhs <- c("XA", "XB", "XB", "XA", "p1/a1", "p2/a2")
    label <- c("a1", "a2", "p1", "p2", "k1", "k2")
    est <- c(paramList$Actor_A$slopeValue, paramList$Actor_B$slopeValue,
             paramList$Partner_A$slopeValue, paramList$Partner_B$slopeValue,
             (paramList$Partner_A$slopeValue/paramList$Actor_A$slopeValue), (paramList$Partner_B$slopeValue/paramList$Actor_B$slopeValue))
    se <- c(rep(NA, 6))
    z <- c(rep(NA, 6))
    pvalue <- c(rep(NA, 6))
    ci.lower <- c(rep(NA, 6))
    ci.upper <- c(rep(NA, 6))
    std.lv <- c(rep(NA, 6))
    std.all <- c(rep(NA, 6))
    std.nox <- c(rep(NA, 6))

    sim.param <- data.frame(lhs, op, rhs, label, est, se, z, pvalue, ci.lower, ci.upper, std.lv, std.all, std.nox)

    sim.param$pop_model <- "L_APIM"
    sim.param$samp_model <- NA
    sim.param$samp_n <- NA

    sim.param <- sim.param %>%
      dplyr::relocate(.data$pop_model, .data$samp_model, .data$samp_n)
  }else if(paramType == "both"){

  }else{
    stop("paramType can only either be measurement, structural, or both")
  }
  return(sim.param)
}
